apiVersion: v1
kind: Service
metadata:
  name: karpov-av-bivt-22-5 #Задайте name со своими инициалами и группой. Example: karpov-av-bivt-22-5
spec:
  selector:
    app: student-app
  ports:
  - port: 80
    targetPort: 80
  type: NodePort
