apiVersion: v1
kind: Service
metadata:
  name: demo-nginx-svc
spec:
  type: LoadBalancer
  selector:
    app: demo-nginx
  ports:
    - port: 80        # Порт сервиса
      targetPort: 80  # Порт контейнера (из Deployment)
