apiVersion: v1
kind: Service
metadata:
  name: student-app-service
  namespace: student-workspace
  labels:
    owner: STUDENT_NAME_GROUP
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: student-app
